[package]
name = "game-theory"
version = "0.1.0"
authors = ["Eric Walkingshaw <eric@walkingshaw.net>"]
edition = "2021"
description = "A game theory toolbox."
repository = "https://github.com/walkie/game-theory-rust/"

[dependencies]
derive_more = "0.99"
num = "0.4"
probability = "0.17"
